apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-devops-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: irohitmishra/java_devops_pipeleine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: java-devops-minikubesvc
spec:
  type: NodePort
  selector:
      app: demoapp
  ports:
   - protocol: "TCP"
     port: 8080
     targetPort: 8080
     nodePort: 30010


 